language: ruby
rvm:
- 2.1
  
# Containers are cool!  
sudo: false

install: 
- bundle install
- pip install --user awscli
- ~/.local/bin/aws configure set preview.cloudfront true
  
# Build and deploy the site to the S3 bucket on push to master, unless PR
script: bundle exec jekyll build
branches:
  only:
  - master
deploy:
  provider: s3
  access_key_id: AKIAI5BHYTATVTT4KOHA
  secret_access_key:
    secure: "PxdiSKmbSo3eT9odb9pzofhV5wslw8X+Mdhykc+gc8jXhRXj0hsy/LZuknU9QSjlWR+mn90wpLYitAY24XK9N64syhjGxQFs+3qFYiSrvN+IexPTMDaXIOWzz7rYKJe0qTbyUEuGFSzzdaAPBhVNzyC1kzBIE3RJIhZ63lX/Bn/jZr2SpXBMC3hGE+fv/JiQrEecA4ZubI/A/RI2ptZUIMwkoRA58KOYcMqYe2UBFQwPX6n1VaN3wjraVkN3xC2wk/dNqysRJD6OjpDuYmY0fR0807cRp2ICKq4DqqXfFkEBOJpyN0ygmEHdlWor2hKINRwN28gZ5CHwGHU1AkLF24whGZOx1X7IrPMCS7wM98dTTr+vmJxTxY27LrHoDCAi9mzKIF/W7QSPpI6qdCIHIuYmiIAXt0xsOgMTL+6FYvXS6C/7o3lcUgcAEqb7xRDurrcWZ1ULdeJ6+e1shtFe7D9vSirTOGwqp/JdD6BtVl5RpWYu0PvU6fjyJV5NgFWT6nMCMaj0o07KXTw3/fJdZUDC3QaKYS5pDBxgOyYeERp5Zwmo3dTzkLcehvlhSzfrWiDwmIQeV6qTgggudF7g4ddQPDgBdZkIXbWXu1mzsMeJ9pAtKQ6I9yfxpZTnTmXI9SzhZ77wI6lNVv9t34nEmv72b5SqEcUKcCUidPeWbHc="
  bucket: rust-vietnam-www
  acl: public_read
  skip_cleanup: true
  local_dir: _site
  region: ap-southeast-1
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = "false"

after_success: 
- '[[ $TRAVIS_PULL_REQUEST == "false" ]] && python invalidation-list.py'

after_deploy:
- '[[ $TRAVIS_PULL_REQUEST == "false" ]] && ~/.local/bin/aws cloudfront create-invalidation
  --invalidation-batch file://payload.json --distribution-id E2JAXTWKB7NE6G'
