language: ruby
rvm:
- 2.1
  
# Containers are cool!  
sudo: false

install: 
- bundle install
- pip install --user awscli
- ~/.local/bin/aws configure set preview.cloudfront true
  
# Build and deploy the site to the S3 bucket on push to master, unless PR
script: bundle exec jekyll build
branches:
  only:
  - master
deploy:
  provider: s3
  access_key_id: AKIAJCFW25SXOIBZTZ7Q
  secret_access_key:
    secure: "m3LdnEQh0HYNC7Y1h0wNjXWwfPfOrq6dsAyw0wwhUjW+JtWUW+eJJxMeyZ4fUzeU6uLKMLwfQTzSoW/ztUpnKm5jU5unR5qzOKI6lr8YwuRIxsNp/3FMTzRfW208vxV1W9UjxyQf4V9PUPxV7WURrnTs5Hc/daXSMYxfJDxx4cQBAYN+1OH5eAacncVlC6K0etyMHw7dYe8Ztlp9cLiI1DRgsFRNndSsbQXy9kuPU7cIT3CNGOZk9PyLNSx7KS/nZIaYUhz8kFbUo4ei0pFbWC5lOe7ZWEjkQH2q1k88CbX2wFDNniIfGQ1QdzRofqx/rPy1Cj79hNLxcYmJzl+NzzeU/RpOC0LH6xMAslkpqHG8kVHGwP3n4UGdooJ4CKed4n7m88sZjfFHr3/lMLOUi6E5E1WqaalLs47ijpJqXr4wDDHqZYr7QWaKCVnfkvEXWOidLOB0NrjobbDHjkI/BcE9LIJDDApKn+e/1qGZTU4HFshBqMbz091Sc6DMB9dmCrbnkddcrCXjw595pya1TiJ1txfSD7sFzcBR86GkyugBnnGtzmRu1bTGNu32ci4+3yQ52TlD6+dvp8ZMKgVIuItK1sS43DyzO8jkNDy2f/6gYUy9P70ovspP+ePfM72b410NEtoCt8xbon+/KgNJOzk1MCT0dCH187B/3CETApQ=" 
  bucket: rust-vietnam-www
  acl: public_read
  skip_cleanup: true
  local_dir: _site
  region: ap-southeast-1
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = "false"

after_success: 
- '[[ $TRAVIS_PULL_REQUEST == "false" ]] && python invalidation-list.py'

after_deploy:
- '[[ $TRAVIS_PULL_REQUEST == "false" ]] && ~/.local/bin/aws cloudfront create-invalidation
  --invalidation-batch file://payload.json --distribution-id E2JAXTWKB7NE6G'
