language: ruby
rvm:
- 2.1
  
# Containers are cool!  
sudo: false

install: 
- bundle install
- pip install --user awscli
- ~/.local/bin/aws configure set preview.cloudfront true
  
# Build and deploy the site to the S3 bucket on push to master, unless PR
script: bundle exec jekyll build
branches:
  only:
  - master
deploy:
  provider: s3
  access_key_id: AKIAJCFW25SXOIBZTZ7Q
  secret_access_key:
    secure: "RTdWOi8rPopFE8dh8+tzv2z2YC7ZE6REjeIb+hbj7nr8Or6QWBZJWmg/22+6RzMdcTVUiWBmABfl1QO9pfk6tUQiXCFZgs0DhZsaUQx5ygiUHwqYvcBUBXKN5qKPmVTisO0JZAvTbL5uWxvHBEFg8Y3QVeKKt5AFA3vHhEIWXhS/K22eVaxGZMOW++oj0lwG+I1pHXpTRGavtPdV8IWcAHFnIf491WBFR3Y4NcczKka4ziUJMj8srPTS54AS/7cXv3PVyMLl7p/OP7tuSCksQBbv+5iIe6xJY2bOwDa3ovUl7ujZD/+XEb8QS+/nukUS8ygfc/do4n6xTY1cqnVQAG2G6IeBe34fG36JLDxY5BpilSMOuJLqLkFhSg/b7iq6b3tCPE0/4Jm+lbNzNeV6PB1MtkiSb5VLtwOM/HDzGNURA0MYWdbfKDmv2clw5trCEKEqMgq/dW842mRQ3SAzJtYScdTVLkDlFT+2b97J0EzQfcjyrtccbUDtHXCX5pdw/lhF0P+qszrjhDISLyZk7bt5YTQTlgKxanc8gCnAFuDSkJXDSOGGNkInbbksRZwnvxWBT5tghUXgITSL9JuGHiWbLZLjMSKcAMFNUy/8tTOk/LJPkoUAZQ1RKadgZh0q2/yTlB09cJXY4OTptjixbCB+tBwCBN1im/dBV2LUgJk="
  bucket: rust-vietnam-www
  acl: public_read
  skip_cleanup: true
  local_dir: _site
  region: ap-southeast-1
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = "false"

after_success: 
- '[[ $TRAVIS_PULL_REQUEST == "false" ]] && python invalidation-list.py'

after_deploy:
- '[[ $TRAVIS_PULL_REQUEST == "false" ]] && ~/.local/bin/aws cloudfront create-invalidation
  --invalidation-batch file://payload.json --distribution-id E2JAXTWKB7NE6G'
