name: Ngôn ngữ lập trình Rust 
stable: "1.13.0"
stable_date: "2016-11-10"
stable_blog: "https://blog.rust-lang.org/2016/11/10/Rust-1.13.html"
stable_full_version: "rustc 1.13.0 (2c6933acc 2016-11-07)"
beta: "1.14"
beta_date: "2016-12-22"
nightly: "1.15"
channels:
    - name: "stable"
      vers: "1.13.0"
      package: "1.13.0"
    - name: "beta"
      vers: "1.14"
      package: "beta"
    - name: "nightly"
      vers: "1.15"
      package: "nightly"
global_domain: "https://www.rust-lang.org"
