name: Ngôn ngữ lập trình Rust 
stable: "1.13.0"
stable_date: "2016-11-10"
stable_blog: "/2016/11/10/Rust-1.13.html"
beta: "1.14"
beta_date: "2016-12-22"
nightly: "1.15"
global_domain: "https://www.rust-lang.org"
