name: Ngôn ngữ lập trình Rust 
stable: "1.14.0"
stable_date: "2016-12-22"
stable_blog: "https://blog.rust-lang.vn/2016/12/22/ver-1-14-release-notes.html"
stable_full_version: "rustc 1.14.0 (2c6933acc 2016-11-07)"
beta: "1.15"
beta_date: "2017-02-02"
nightly: "1.16"
channels:
    - name: "stable"
      vers: "1.14.0"
      package: "1.14.0"
    - name: "beta"
      vers: "1.15"
      package: "beta"
    - name: "nightly"
      vers: "1.16"
      package: "nightly"
global_domain: "https://www.rust-lang.org"
